/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import java.sql.Connection;
import util.connectionFactory;

public class Main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Main().getGreeting());
        
        Connection c = connectionFactory.getConnection();
        
        connectionFactory.closeConnection(c);
    }
}
